[package]
name = "arugio_client"
version = "0.1.0"
authors = ["ostwilkens <carl@ostwilkens.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arugio_shared = { path = "../arugio_shared" }
bevy_webgl2 = { git = "https://github.com/mrk-its/bevy_webgl2", rev = "a724cdf6b6392e3d0b185112a34c011987b8dc63" }
console_log = "0.2"
log = "0.4"
console_error_panic_hook = "0.1.6"

[dependencies.bevy]
git = "https://github.com/bevyengine/bevy"
rev = "01ba7c44255059f833c2b90d3d6b7ac7e9c025ca"
default-features = false

[dependencies.bevy_networking_turbulence]
git = "https://github.com/ostwilkens/bevy_networking_turbulence"
rev = "41145b318e71008b48cdcd8b40140bb88bef868d"
default-features = false
features = ["use-webrtc"]
